import './global.css';
import Head from 'next/head';

export const metadata = {
  title: 'Welcome to physlane',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>Welcome to site!</title>
      </Head>
      <body>{children}</body>
    </html>
  );
}
